building new parse

diff --git a/parse b/parse
--- a/parse
+++ b/parse
@@ -6,6 +6,55 @@ set -e
 format='.*(webrip|avi|flv|wmv|mov|mp4|mkv|3gp|webm|m4a|m4v|f4a|f4v|m4b|m4r|f4b).*</a>'
 ct=.ct;ct2=.ct2;out=.out;out2=.out2;name="parse";directory=~/.parseHub;arch=$(uname)
 
+resize(){
+	file=.resizer.txt
+	if [ ! -d resized_images ]; then mkdir resized_images;fi
+	if [ ! -d original_images ]; then mkdir original_images;fi
+	if [[ -e $file ]]; then rm $file;fi
+	find *.jpg *.png *.jpeg 2> /dev/null|grep -vE '(_c.jpg|_c.png|_c.jpeg)'|grep -n . > $file|| printf "\\r:: no images to convert\\n"
+	cnt=1; mul=0; numberOfImgs=$(wc -l .resizer.txt|sed "s/ .resizer.txt//"); z=0
+	while true;do
+		if grep -q "$cnt:" $file; then
+			printf %b ":: resizing $numberOfImgs images to 500x741: $mul%\\r"
+			name=$(grep -w "$cnt:.*" $file|sed "s/"$cnt:"//")
+			extension=$(grep "$name" $file|grep -oE '(.jpg|.png|.jpeg)')
+			identify=$(identify -verbose "$name" 2>> .logs|grep Geometry|sed -e 's/.*: //' -e 's/+.*//' -e 's/x//')
+			geometry=$(echo $identify|sed 's/x//')
+			width=$(echo $identify|sed 's/x.*//')
+			height=$(echo $identify|sed 's/.*x//')
+			if [[ $extension == '.jpg' ]];then
+				old='.jpg';new='_c.jpg'
+			elif [[ $extension == '.png' ]]; then
+				old='.png';new='_c.png'
+			elif [[ $extension == '.jpeg' ]]; then
+				old='.jpeg';new='_c.jpeg'
+			fi
+			new_name=$(grep -w "$cnt:.*" $file|sed "s/"$cnt:"//"|sed "s/$old/$new/")
+			if [[ $geometry -lt 500741 ]]; then
+				echo "$name is less than 500x741" >> .logs
+			elif [[ $geometry -gt 500741 ]]; then
+				convert "$name" -resize 500x741! -quality 55 resized_images/"$new_name" 2>> .logs
+				mv "$name" original_images/		#~/.local/share/Trash/files
+			elif [[ $geometry == 500741 ]]; then
+				convert "$name" -quality 55 resized_images/"$new_name" 2>> .logs
+				mv "$name" original_images/		#~/.local/share/Trash/files
+			fi
+			div=$(((100+(numberOfImgs-1))/numberOfImgs)); mod=$((100%div)); cnt=$((cnt+1)); z=$((z+1));
+			if [ $mod == 0 ]; then mul=$((div*z)); fi
+			if [ $z == $numberOfImgs ]; then
+				mul=$((mul+mod))
+				echo ":: resizing $numberOfImgs images to 500x741: $mul%"
+				echo ":: saved to resized directory."
+				break
+			fi
+			if [ $mod != 0 ]; then mul=$((div*z)); fi
+		else
+			break
+		fi
+	done
+	rm $file
+}
+
 cleanup(){
 	if [ -e .out ]; then rm .out*; fi
 	if [ -e .ct ]; then rm .ct*; fi
@@ -23,7 +72,7 @@ abort(){
 	if [ "$nd2" != '' ]; then echo > /dev/null
 	else echo -e "aborted.\\n"
 	fi
-	exit 0		
+	exit 0
 }
 
 title(){
@@ -104,12 +153,12 @@ connect(){
 
 dl(){
 	#axel and aria2
-	wget -k "$url" -o .wget -O $ct||connect
+	wget -k "$url" -o .wget -O $ct ||connect
 	if ! grep -qE "$format" $ct; then
 		if [ "$nd2" != '' ];then echo -e ":: error: $url\\n" else echo -e "error: $url\\n";fi
 		abort
 	fi
-	if grep -qiqE '(&amp|&darr)' $ct; then grep -vE '.*(amp|darr).*' $ct > $ct2;mv $ct2 $ct;fi
+	if grep -qiE '(&amp|&darr)' $ct; then grep -vE '.*(amp|darr).*' $ct > $ct2;mv $ct2 $ct;fi
 	if grep -qioE "trailer" $ct; then echo 'Trailer' >> $out
 		{
 			grep -iwE ".*trailer.*</a>" $ct|sed 's:.*<a:<a:';echo
@@ -127,7 +176,7 @@ final(){
 			#get 480p, 720p & 1080p only
 			if grep -qioE "$f" "$file"; then grep -E "$f" "$file" > $ct2
 				if grep -qE "(x264|x265)" $ct2; then
-					perg(){ 
+					perg(){
 						size=$(wc -l<.ct3)
 						if [ "$size" -ge 1 ]; then
 							{
@@ -152,60 +201,11 @@ final(){
 				if grep -qioE "$f.*x265" $ct2; then
 					{
 						echo -e "\\n$f x265\\n"; grep -oiE ".*$f.*x265" $ct2
-					} >> $out 
+					} >> $out
 				fi
 			fi
 		done
 	fi
-}
-
-resize(){
-	file=.resizer.txt
-	if [ ! -d resized_images ]; then mkdir resized_images;fi
-	if [ ! -d original_images ]; then mkdir original_images;fi
-	if [[ -e $file ]]; then rm $file;fi
-	find *.jpg *.png *.jpeg 2> /dev/null|grep -vE '(_c.jpg|_c.png|_c.jpeg)'|grep -n . > $file|| printf "\\r:: no images to convert\\n"
-	cnt=1; mul=0; numberOfImgs=$(wc -l .resizer.txt|sed "s/ .resizer.txt//"); z=0
-	while true;do
-		if grep -q "$cnt:" $file; then
-			printf %b ":: resizing $numberOfImgs images to 500x741: $mul%\\r"
-			name=$(grep -w "$cnt:.*" $file|sed "s/"$cnt:"//")
-			extension=$(grep "$name" $file|grep -oE '(.jpg|.png|.jpeg)')
-			identify=$(identify -verbose "$name" 2>> .logs|grep Geometry|sed -e 's/.*: //' -e 's/+.*//' -e 's/x//')
-			geometry=$(echo $identify|sed 's/x//')
-			width=$(echo $identify|sed 's/x.*//')
-			height=$(echo $identify|sed 's/.*x//')
-			if [[ $extension == '.jpg' ]];then
-				old='.jpg';new='_c.jpg'
-			elif [[ $extension == '.png' ]]; then
-				old='.png';new='_c.png'
-			elif [[ $extension == '.jpeg' ]]; then
-				old='.jpeg';new='_c.jpeg'
-			fi
-			new_name=$(grep -w "$cnt:.*" $file|sed "s/"$cnt:"//"|sed "s/$old/$new/")
-			if [[ $geometry -lt 500741 ]]; then
-				echo "$name is less than 500x741" >> .logs
-			elif [[ $geometry -gt 500741 ]]; then
-				convert "$name" -resize 500x741! -quality 55 resized_images/"$new_name" 2>> .logs
-				mv "$name" original_images/		#~/.local/share/Trash/files
-			elif [[ $geometry == 500741 ]]; then
-				convert "$name" -quality 55 resized_images/"$new_name" 2>> .logs
-				mv "$name" original_images/		#~/.local/share/Trash/files
-			fi
-			div=$(((100+(numberOfImgs-1))/numberOfImgs)); mod=$((100%div)); cnt=$((cnt+1)); z=$((z+1));
-			if [ $mod == 0 ]; then mul=$((div*z)); fi
-			if [ $z == $numberOfImgs ]; then
-				mul=$((mul+mod))
-				echo ":: resizing $numberOfImgs images to 500x741: $mul%"
-				echo ":: saved to resized directory."
-				break
-			fi
-			if [ $mod != 0 ]; then mul=$((div*z)); fi
-		else
-			break
-		fi
-	done
-	rm $file
 }
 
 parser(){
@@ -219,7 +219,7 @@ parser(){
 			if grep -qioE "$f.*$format" $ct; then
 				grep -owE ".*$f.*$format" $ct > $ct2
 				if grep -qE "(x264|x265)" $ct2; then
-					perg(){ 
+					perg(){
 						size=$(wc -l<.ct3)
 						if [ "$size" -ge 1 ]; then
 							{
@@ -252,67 +252,24 @@ parser(){
 			fi
 		done
 	fi
+	if [ $enabled_alternate ]; then
+		grep -oi '.*Season.*' $out|head -1 >> $out2
+		alternate_flag=$(echo $alternate_flag|sed "s/-//")
+		grep -iw ".*$alternate_flag.*" $out >> $out2
+		mv $out2 $out
+	fi
+
 	if [ -e $ct2 ]; then rm .ct[2-3];fi
 }
 
 header(){
-	if [ "$1" == top ]; then
-		echo -e "[vc_row][vc_column column_width_percent=\"100\" align_horizontal=\"align_center\" overlay_alpha=\"50\" gutter_size=\"3\" medium_width=\"0\" mobile_width=\"0\" shift_x=\"0\" shift_y=\"0\" shift_y_down=\"0\" z_index=\"0\" width=\"1/1\"][vc_column_text]\\n\\n>>>  paste movie description here  <<<" > $out
-	else
-		echo -e "\\n[/vc_column_text][/vc_column][/vc_row]" >> $out
-	fi
-}
-
-edit(){
-	if [ "$1" == '' ]; then pixel=url;printf %b "          [paste any valid URL]\\r"
-	else pixel=$1;printf %b "          [paste only $pixel URLs]\\r"
-	fi
-	read -erp "$pixel: " url
-	if [ "$url" == "" ]; then
-		abort
-	else
-		lru=$(echo "$url"|grep "http" || echo false)
-		if [ "$lru" == false ]; then echo -e "error: $url.";b=$((b-1));edit;fi
-	fi
-	if [ ! -e $directory/.conf ]; then title='DEFAULT'
-	else title=$(grep "AUTO_ADD_TITLE=" $directory/.conf|sed "s/AUTO_ADD_TITLE=//")
-	fi
-	if [ "$title" == DEFAULT ];then printf %b "                   [Y/n]\\r"
-		read -n 1 -erp "add title?: " t
-	elif [ "$title" == YES ]; then
-		t=y
-	else
-		t=n
-	fi
-	if [ ! -e $directory/.conf ]; then header='NO'
-	else header=$(grep "UNIVERSAL_HEADER=" $directory/.conf|sed "s/DEFAULT_HEADER=//")
-	fi
-	if [ "$1" == '' ]; then
-		if [ "$header" == YES ]; then header top
-			if [ "$t" == y ]||[ "$t" == '' ]; then dl;title;PIO;else dl;PIO;fi
-			header
+	if [ $flag_for_header == -p ]; then
+		if [ "$1" == top ]; then
+			echo -e "[vc_row][vc_column column_width_percent=\"100\" align_horizontal=\"align_center\" overlay_alpha=\"50\" gutter_size=\"3\" medium_width=\"0\" mobile_width=\"0\" shift_x=\"0\" shift_y=\"0\" shift_y_down=\"0\" z_index=\"0\" width=\"1/1\"][vc_column_text]\\n\\n>>>  paste movie description here  <<<" > $out
 		else
-			if [ "$t" == y ]||[ "$t" == '' ]; then dl;title;PIO;else dl;PIO;fi
-		fi
-	else
-		dl
-		if ! grep -q "$pixel" $ct; then echo -e "$pixel: no such text.\\n";abort
-		else
-			if [ "$header" == YES ]; then header top
-				PIO; mv $out $out2
-				if [ "$t" == y ]||[ "$t" == '' ]; then title; fi
-				grep -iwE "$1" $out2 >> $out; rm $out2;header
-			else
-				PIO; mv $out $out2
-				if [ "$t" == y ]||[ "$t" == '' ]; then title; fi
-				grep -iwE "$1" $out2 >> $out; rm $out2
-			fi
+			echo -e "\\n[/vc_column_text][/vc_column][/vc_row]" >> $out
 		fi
 	fi
-	if [ "$arch" == "Darwin" ]; then pbcopy < $out;else xclip -sel clip < $out;fi
-	echo -e "copied to clipboard."
-	rm $out $ct .wget
-	if [ "$1" != -u ]||[ "$1" != -d ]; then update;fi;edit "$1"
 }
 
 sort(){
@@ -333,7 +290,7 @@ sort(){
 			status=0
 		fi
 	}
-	_dir=".editmp";if [ ! -d $_dir ];then mkdir $_dir;fi;a=0;b=1;d=0;escape=$(echo "$escape")
+	_dir=".editmp";if [ ! -d $_dir ];then mkdir $_dir;fi;a=0;b=1;d=0; #escape=$(echo "$escape")
 	while true;do
 		if [ $b -ge 10 ]; then d="";srt="$d$b"
 		elif [ $b -le 10 ]; then if [ $b -eq 0 ]; then b=1; else d=0;srt="$d$b";fi
@@ -356,7 +313,7 @@ sort(){
 						echo -e ":: copied to clipboard.\\n";rm $out;return
 					fi;;
 				*)
-					lru=$(echo "$url"|grep "http"|| echo false)
+					lru=$(echo "$url"|grep "http"||echo false)
 					if [ "$lru" == false ]; then
 						echo -e "\\n:: error: $url\\n"
 							echo > $out;size=$(wc -l<$out);abort
@@ -374,14 +331,25 @@ sort(){
 
 trap sig_abort SIGINT;cleanup
 case $1 in
-	""|480p|480P|720p|720P|1080p|1080P)	echo;edit "$1";;
-	-p)
+	""|-480p|-480P|-720p|-720P|-1080p|-1080P) ;;
+	-p|-P)
+		flag_for_header=$1
 		touch $out
-		if [ "$2" != '' ]; then
+		if [ "$2" == '' ]; then
+			echo -e ":: no links added.";cleanup
+		else
+			if [ "$2" == -480p ]||[ "$2" == -720p ]||[ "$2" == -1080p ]; then
+				if [ "$3" == '' ]; then echo -e ":: no links added.";cleanup && exit;fi
+			fi
 			escape=no;nd2="$2";n=$(($#-1));mul=0;z=0
 			echo
 			for position;do
-				if [ "$position" == -p ]; then
+				if [ "$position" == -p ]||[ "$position" == -P ]; then
+					continue
+				elif [ "$position" == -480p ]||[ "$position" == -720p ]||[ "$position" == -1080p ];then
+					alternate_flag="$position"
+					enabled_alternate=yes
+					n=$(($#-2))
 					continue
 				else
 					printf %b ":: auto parsing $n URL(s): $mul%\\r"
@@ -389,6 +357,7 @@ case $1 in
 					if [ "$status" == 1 ]; then
 						if grep -qo "404" .wget; then fb="404 not found"
 						elif grep -qo "521" .wget; then fb="origin down"
+						else fb="unknown error"
 						fi
 						echo -e ":: $fb: $url.\\n";abort
 					fi
@@ -401,25 +370,13 @@ case $1 in
 			fi
 			if [ $mod != 0 ]; then mul=$((div*z)); fi
 			done
-			escape=yes; printf %b ":: assembling...\\r";sleep 1
-			'sort' "$n";if [ "$1" != -u ]||[ "$1" != -d ]; then update;fi;abort
-		else
-			echo -e ":: no links added.";cleanup
+			escape=yes; #printf %b ":: assembling...\\r";sleep 1
+			'sort' "$n"; abort
+		#else
+		#	echo -e ":: no links added.";cleanup
 		fi;;
-	-u)
-		if [ ! -e "$directory" ];then echo -e ":: standalone script: updates disabled.";exit
-		else
-			echo "checking for updates...";
-			cd "$directory"
-			if [ -e url_parser ];then
-				(cd url_parser
-				git pull -q 2> /dev/null||connect_)
-				bash url_parser/install_parse.sh
-			else
-				printf "error: reinstall $name."
-			fi
-		fi;;
-	-r)	
+	-u) ;;
+	-r)
 		resize
 		if [ -e .logs ]; then
 			size=$(wc -l .logs|sed "s/ .logs//")
@@ -429,22 +386,6 @@ case $1 in
 			fi
 			rm .logs
 		fi;;
-	-e) 
-		if [ ! -e "$directory" ];then echo -e ":: standalone script: configuration unavailable."
-		else nano "$directory"/.conf;fi;;
-	-d)
-		if [ ! -e "$directory" ];then echo -e ":: standalone script: uninstall unavailable.";exit;fi
-		if [ "$arch" = Linux ]; then inst_dir=/usr/bin/$name
-		elif [ "$arch" = Darwin ]; then inst_dir=/usr/local/bin/$name
-		fi
-		if [ -e $inst_dir ]; then sudo rm -rf $inst_dir $directory;echo "$name: uninstalled."
-		else echo "$name is not installed"
-		fi;;
-	-v) echo -e "$name $version.\\nThis is free software: you are free to change and redistribute it.\\nWritten by looneytkp. <https://github.com/looneytkp/url_parser>.";;
-	-h)	
-		if [ ! -e "$directory" ];then echo -e ":: standalone script: help info unavailable.";exit;fi
-		if [ -d "$directory" ]; then cat "$directory"/.help;fi;;
-	*)	echo -e "invalid flag: $1."
-		if [ -d "$directory" ]; then cat "$directory"/.help;fi;;
+	*)	echo -e "\\ninvalid flag: $1.\\n";;
 esac
 #end of script
