fixes

diff --git a/testing/test-fixed movies b/testing/test-fixed movies
--- a/testing/test-fixed movies
+++ b/testing/test-fixed movies
@@ -1,7 +1,6 @@
 #!/bin/bash
 # by_looneytkp #
 set -e
-start=`date +%s`
 # function to install parse #
 install(){
 which parse > /dev/null || stat=1
@@ -25,11 +24,11 @@ if [ $stat ]; then echo ":: install xclip." && exit; fi
 }
 #install
 # variables #
-format='.*(avi|flv|wmv|mov|mp4|mkv).*</a>' # format #
+format='.*(avi|flv|wmv|mov|mp4|mkv)</a>' # format #
 tmp_directory="$PWD/.temp"; PIO_directory="$PWD/.PIO"; summary_directory="$PWD/.finished" # directories #
 ct="$tmp_directory/xy"; ct2="$tmp_directory/yx"; out=.parsed # files #
 sig_abort(){
-	cleanup && echo -e "\\n:: aborted.\\n" && exit 0
+	cleanup && echo -e "\\naborted.\\n" && exit 0
 }
 cleanup(){
 	# clean up residues before and after execution #
@@ -41,14 +40,8 @@ connect(){
 	if [ $exitStatus == 0 ]; then
 		if grep -q "404" "$tmp_directory"/.wget; then
 			echo -e "\\n:: error $counter: $positional_parameter\\n:: 404 not found.\\n"
-		elif grep -q "service not known" "$tmp_directory"/.wget; then
+		elif grep -q "Name or service not known" "$tmp_directory"/.wget; then
 			echo -e "\\n:: error $counter: $positional_parameter\\n:: service unknown.\\n"
-		elif grep -q "Connection refused" "$tmp_directory"/.wget; then
-			echo -e "\\n:: error $counter: $positional_parameter\\n:: connection refused.\\n"
-		elif grep -q "503" "$tmp_directory"/.wget; then
-			echo -e "\\n:: error $counter: $positional_parameter\\n:: service temporarily unavailable.\\n"
-		elif grep -q "timed out" "$tmp_directory"/.wget; then
-			echo -e "\\n:: error $counter: $positional_parameter\\n:: connection timed out.\\n"
 		fi
 	else
 		echo -e "\\n:: no internet connection.\\n"
@@ -58,21 +51,20 @@ connect(){
 
 
 parsing(){
-set -x
 	if [ "$#" != 0 ]; then
 
 		# download html file #
-		wget --timeout=10 --waitretry=0 --tries=2 --retry-connrefused -k "$positional_parameter" -o "$tmp_directory"/.wget -O "$ct" || connect	##
+		wget -k "$positional_parameter" -o "$tmp_directory"/.wget -O "$ct" || connect	##
 
 		# removes needed text, excluding junk #
 		grep -iowE "<a href=$format" "$ct" | grep -vE '.*(amp|darr).*' > "$ct2" && mv "$ct2" "$ct" || stat=$?	##
-		if [ $stat ]; then echo -e "\\n:: error: $positional_parameter\\n"; cleanup && exit; fi
+		if [ $stat ]; then echo -e ":: error: $positional_parameter\\n"; cleanup && exit; fi
 
 		# get trailers if available #
 		# get trailer code goes here #
 
 		# gets season tag of current url and create a text file for it #
-		title=$(grep -io "s[0-9][0-9]" "$ct"|head -1|sed -e "s/[S-s]/<h3>Season /" -e 's/$/<\/h3>/' || grep -io "s[0-9]" "$ct"|head -1|sed -e "s/[S-s]/<h3>Season 0/" -e 's/$/<\/h3>/')
+		title=$(grep -ioE "(s[0-9][0-9]|s[0-9])" "$ct"|head -1|sed -e "s/[S-s]/<h3>Season /" -e 's/$/<\/h3>/' || echo movie)
 		tag=$(echo "$title"|grep -o "[0-9][0-9]" || echo movie)
 		if [ ! -e "$summary_directory"/s"$tag" ]; then
 			if [ $tag == movie ]; then
@@ -88,12 +80,9 @@ set -x
 				q=$(grep -E $format "$ct"|head -1|sed -e "s/.*\">//")
 				r=$(echo $q|grep -ioE ".([0-9][0-9][0-9][0-9]|web-dl).*(avi|flv|wmv|mov|mp4|mkv)")
 				omdb=$(echo $q|sed "s/$r.*//")
-				#year=$(grep -E $format "$ct"|head -1|grep -oE '(.)[0-9][0-9][0-9][0-9]'|sed 's/.//'|head -1)
 			else
-				omdb=$(grep -E $format "$ct"|head -1|sed -e "s/.*\">//" -e "s/[S-s][0-9][0-9].*//" -e 's/.[0-9][0-9][0-9][0-9].*//')
-				#year=$(grep -E $format "$ct"|head -1|grep -oE '(.)[0-9][0-9][0-9][0-9]'|sed 's/.//'|head -1)
+				omdb=$(grep -E $format "$ct"|head -1|sed -e "s/.*\">//" -e "s/[S-s][0-9][0-9].*//")
 			fi
-			#if [ $year == '' ]||[ $year == 1080 ]||[ $year == 2160 ]; then unset year; fi
 		fi
 
 		# loop orderly to parse pixel resolutions #
@@ -132,11 +121,7 @@ set -x
 		# adds alignment & movie description #
 		if [ ! "$no_alignment" ]; then
 			echo -e "[vc_row][vc_column column_width_percent=\"100\" align_horizontal=\"align_center\" overlay_alpha=\"50\" gutter_size=\"3\" medium_width=\"0\" mobile_width=\"0\" shift_x=\"0\" shift_y=\"0\" shift_y_down=\"0\" z_index=\"0\" width=\"1/1\"][vc_column_text]" >> $out
-			if [ $tag == movie ]; then
-				curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?t=$omdb&type=Movie&plot=short&apikey=7759dbc7" -o "$tmp_directory"/description
-			else
-				curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?t=$omdb&type=Series&plot=short&apikey=7759dbc7" -o "$tmp_directory"/description
-			fi
+			curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?t=$omdb&apikey=7759dbc7" -o "$tmp_directory"/description	# omdb api #
 			if grep -qiE "(Movie not found!|error)" "$tmp_directory"/description; then
 				echo -e "\\n>>>  paste movie description here  <<<" >> $out
 			else
@@ -147,7 +132,7 @@ set -x
 
 		# finalize parsing by sorting resolutions, add titles  & copy to clipboard
 		for file in "$summary_directory"/*; do
-			title=$(grep -io "s[0-9][0-9]" "$file"|head -1|sed -e "s/[S-s]/<h3>Season /" -e 's/$/<\/h3>/' || grep -io "s[0-9]" "$ct"|head -1|sed -e "s/[S-s]/<h3>Season 0/" -e 's/$/<\/h3>/')
+			title=$(grep -ioE "(s[0-9][0-9]|s[0-9])" "$file"|head -1|sed -e "s/[S-s]/<h3>Season /" -e 's/$/<\/h3>/')
 			tag=$(echo "$title"|grep -o "[0-9][0-9]" || echo movie)
 			if [ ! "$no_title" ]; then grep -q "$title" $out || echo -e "\\n$title" >> $out; fi
 
@@ -206,7 +191,7 @@ for positional_parameter; do
 		# checks for redundant arguments that aren't urls #
 		check_url=$(echo "$positional_parameter"|grep "http"||echo error)
 		if [ "$check_url" == error ]; then
-			echo -e "\\n:: error $counter: $positional_parameter\\n:: invalid URL.\\n"; cleanup && exit
+			echo -e "\\n:: error $counter: $positional_parameter\\n"; cleanup && exit
 		fi	##
 		parsing "$positional_parameter"
 		# simple algo to calculate progress in percentage #
@@ -221,8 +206,5 @@ for positional_parameter; do
 		counter=$((counter+1))	##
 	fi
 done
-parsing && cleanup #&& exit 0
-end=`date +%s`
-runtime=$( echo "$end - $start" | bc -l )
-echo $runtime
+parsing && cleanup && exit 0
 # end of script #
